name: 'Leetcode Editor Badges'
description: 'Create a progress badge'
author: 'shuzijun'
inputs:
  GH_USERNAME:
    description: "Your GitHub username"
    default: ${{ github.repository_owner }}
    required: false
  COMMIT_MESSAGE:
    description: "Message used for committing changes"
    default: "Update progress badge"
    required: false
  COMMIT_EMAIL:
    description: "Email used for committing changes"
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    required: false
  COMMIT_NAME:
    description: "Name used for committing changes"
    default: "leetcode-editor-bot"
    required: false
  BADGES_FILE:
    description: "File showing badge"
    default: "README.md"
    required: false
  START_SECTION_FLAG:
    description: "Identifies the replacement range"
    default: "<!--START_SECTION_FLAG-->"
    required: false
  END_SECTION_FLAG:
    description: "Identifies the replacement range"
    default: "<!--END_SECTION_FLAG-->"
    required: false
  STATISTICS_DIRECTORY:
    description: "Location of the data directory generated by the plug-in"
    default: ".idea/leetcode/"
    required: false
  LEETCODE_SITE:
    description: "leetcode.com or leetcode.cn"
    default: "leetcode.com"
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
